#!/bin/sh

# based on https://github.com/chebro/calendar-notification/
# added support for multiple months

get_month() {
    ## get the month and year shifted by $1 months from today
    ## NOTE: to handle dates such as May 31s, we shift from the 15th
    ## of the current month, see https://stackoverflow.com/a/13168625
    month_year_shifted=$(date --date="$(date +%Y-%m-15) $1 month" +'%m %Y')
    text=$(cal -m $month_year_shifted)

	month=$(echo "$text" | head -n1)
	heads=$(echo "$text" | head -n2 | tail -n1)
    days=$(echo "$text" | tail -n6)

    if [ $1 -eq 0 ]; then  # highlight current day and month
        month="<u>$month</u>"
        today=$(date '+%e')
        todaystyle="<b><span background='#fff' color='#285577'>$today</span></b>"
        days=$(echo "$days" | sed "s; $today; $todaystyle;" \
                            | sed "s;$today ;$todaystyle ;")
    fi
    printf "%s\n%s\n%s\n" "<b>$month</b>" "<i>$heads</i>" "$days"
}

handle_action() {
	echo $DIFF > "$TMP"

    # for i in $(seq -2 2); do
    #     months="$months\n$(get_month $((DIFF+i)))"
    # done

    months=$(printf "%s\n" \
             "$(get_month $((DIFF-2)))"\
             "$(get_month $((DIFF-1)))"\
             "$(get_month $((DIFF+0)))"\
             "$(get_month $((DIFF+1)))"\
             "$(get_month $((DIFF+2)))")
	footnote="<i>        ~ calendar</i> 󰸗 "

	dunstify -a "dunstdate" "" "${months}\n${footnote}"
}

TMP=${XDG_RUNTIME_DIR:-/tmp}/calendar_notification_month
touch "$TMP"

read -r DIFF < "$TMP"
# DIFF=$(<"$TMP")

case $1 in
	"curr") DIFF=0;;
	"next") DIFF=$((DIFF+1));;
	"prev") DIFF=$((DIFF-1));;
esac

handle_action
